version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8123:8123"
    restart: unless-stopped
